  <?php

  $labels = array(
        'name' => _x( 'Hotels', 'Post Type General Name', 'textdomain' ),
        'singular_name' => _x( 'Hotel', 'Post Type Singular Name', 'textdomain' ),
        'menu_name' => _x( 'Hotels', 'Admin Menu text', 'textdomain' ),
        'name_admin_bar' => _x( 'Hotel', 'Add New on Toolbar', 'textdomain' ),
        'archives' => __( 'Hotel Archives', 'textdomain' ),
        'attributes' => __( 'Hotel Attributes', 'textdomain' ),
        'parent_item_colon' => __( 'Parent Hotel:', 'textdomain' ),
        'all_items' => __( 'All Hotels', 'textdomain' ),
        'add_new_item' => __( 'Add New Hotel', 'textdomain' ),
        'add_new' => __( 'Add New', 'textdomain' ),
        'new_item' => __( 'New Hotel', 'textdomain' ),
        'edit_item' => __( 'Edit Hotel', 'textdomain' ),
        'update_item' => __( 'Update Hotel', 'textdomain' ),
        'view_item' => __( 'View Hotel', 'textdomain' ),
        'view_items' => __( 'View Hotels', 'textdomain' ),
        'search_items' => __( 'Search Hotel', 'textdomain' ),
        'not_found' => __( 'Not found', 'textdomain' ),
        'not_found_in_trash' => __( 'Not found in Trash', 'textdomain' ),
        'featured_image' => __( 'Featured Image', 'textdomain' ),
        'set_featured_image' => __( 'Set featured image', 'textdomain' ),
        'remove_featured_image' => __( 'Remove featured image', 'textdomain' ),
        'use_featured_image' => __( 'Use as featured image', 'textdomain' ),
        'insert_into_item' => __( 'Insert into Hotel', 'textdomain' ),
        'uploaded_to_this_item' => __( 'Uploaded to this Hotel', 'textdomain' ),
        'items_list' => __( 'Hotels list', 'textdomain' ),
        'items_list_navigation' => __( 'Hotels list navigation', 'textdomain' ),
        'filter_items_list' => __( 'Filter Hotels list', 'textdomain' ),
    );
    $args = array(
        'label' => __( 'Hotel', 'textdomain' ),
        'description' => __( '', 'textdomain' ),
        'labels' => $labels,
        'menu_icon' => 'dashicons-store',
        'supports' => array('title', 'editor', 'excerpt', 'thumbnail'),
        'taxonomies' => array(),
        'public' => true,
        'show_ui' => true,
        'show_in_menu' => true,
        'menu_position' => 5,
        'show_in_admin_bar' => true,
        'show_in_nav_menus' => true,
        'can_export' => true,
        'has_archive' => true,
        'hierarchical' => false,
        'exclude_from_search' => false,
        'show_in_rest' => true,
        'publicly_queryable' => true,
        'capability_type' => 'post',
    );
    register_post_type( 'hotel', $args );